"""runner weights: unambiguous names and jockey claim

Revision ID: 2e7b2f773e55
Revises: c717a3cad01f
Create Date: 2026-08-16 19:44:25.022436

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2e7b2f773e55"
down_revision: str | Sequence[str] | None = "c717a3cad01f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("runners", sa.Column("carried_weight_lb", sa.Integer(), nullable=True))
    op.add_column("runners", sa.Column("declared_horse_weight_lb", sa.Integer(), nullable=True))
    # server_default keeps this safe to apply to a populated table: existing rows
    # get 0 (a senior rider) rather than failing the NOT NULL constraint.
    op.add_column(
        "runners",
        sa.Column("jockey_claim", sa.Integer(), nullable=False, server_default="0"),
    )
    op.drop_column("runners", "weight")
    op.drop_column("runners", "actual_weight")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "runners", sa.Column("actual_weight", sa.INTEGER(), autoincrement=False, nullable=True)
    )
    op.add_column("runners", sa.Column("weight", sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column("runners", "jockey_claim")
    op.drop_column("runners", "declared_horse_weight_lb")
    op.drop_column("runners", "carried_weight_lb")
    # ### end Alembic commands ###
