"""initial schema

Revision ID: c717a3cad01f
Revises:
Create Date: 2026-08-16 18:36:35.676197

"""

from collections.abc import Sequence

import pgvector.sqlalchemy
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "c717a3cad01f"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # Must precede the chunks table: its embedding column needs the vector type.
    # Autogenerate does not emit this, so a fresh database would fail without it.
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "chunks",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("source_type", sa.String(length=32), nullable=False),
        sa.Column("source_id", sa.Integer(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("chunk_meta", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("embedding", pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("source_type", "source_id", name="uq_chunk_source"),
    )
    op.create_index(
        "ix_chunks_embedding",
        "chunks",
        ["embedding"],
        unique=False,
        postgresql_using="hnsw",
        postgresql_with={"m": 16, "ef_construction": 64},
        postgresql_ops={"embedding": "vector_cosine_ops"},
    )
    op.create_index(
        "ix_chunks_meta", "chunks", ["chunk_meta"], unique=False, postgresql_using="gin"
    )
    op.create_table(
        "horses",
        sa.Column("horse_id", sa.String(length=32), nullable=False),
        sa.Column("brand_no", sa.String(length=8), nullable=False),
        sa.Column("name_en", sa.String(length=128), nullable=True),
        sa.Column("name_zh", sa.String(length=128), nullable=True),
        sa.Column("country_origin", sa.String(length=32), nullable=True),
        sa.Column("colour", sa.String(length=64), nullable=True),
        sa.Column("sex", sa.String(length=32), nullable=True),
        sa.Column("sire", sa.String(length=128), nullable=True),
        sa.Column("dam", sa.String(length=128), nullable=True),
        sa.Column("retired", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("horse_id"),
    )
    op.create_index(op.f("ix_horses_brand_no"), "horses", ["brand_no"], unique=False)
    op.create_index(op.f("ix_horses_name_en"), "horses", ["name_en"], unique=False)
    op.create_index(op.f("ix_horses_name_zh"), "horses", ["name_zh"], unique=False)
    op.create_table(
        "ingest_runs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("source", sa.String(length=64), nullable=False),
        sa.Column("race_date", sa.Date(), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.CheckConstraint(
            "status IN ('running', 'ok', 'failed', 'fallback_detected', 'report_pending')",
            name="ck_ingest_status",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_ingest_runs_date", "ingest_runs", ["race_date"], unique=False)
    op.create_table(
        "jockeys",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name_en", sa.String(length=128), nullable=False),
        sa.Column("name_zh", sa.String(length=128), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name_en", name="uq_jockey_name_en"),
    )
    op.create_index(op.f("ix_jockeys_name_en"), "jockeys", ["name_en"], unique=False)
    op.create_index(op.f("ix_jockeys_name_zh"), "jockeys", ["name_zh"], unique=False)
    op.create_table(
        "meetings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("race_date", sa.Date(), nullable=False),
        sa.Column("racecourse", sa.String(length=2), nullable=False),
        sa.Column("going", sa.String(length=64), nullable=True),
        sa.Column("source_url", sa.Text(), nullable=True),
        sa.Column("fetched_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("race_date", "racecourse", name="uq_meeting_date_course"),
    )
    op.create_index(op.f("ix_meetings_race_date"), "meetings", ["race_date"], unique=False)
    op.create_table(
        "trainers",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name_en", sa.String(length=128), nullable=False),
        sa.Column("name_zh", sa.String(length=128), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name_en", name="uq_trainer_name_en"),
    )
    op.create_index(op.f("ix_trainers_name_en"), "trainers", ["name_en"], unique=False)
    op.create_index(op.f("ix_trainers_name_zh"), "trainers", ["name_zh"], unique=False)
    op.create_table(
        "watermarks",
        sa.Column("source", sa.String(length=64), nullable=False),
        sa.Column("last_race_date", sa.Date(), nullable=True),
        sa.Column("last_run_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("source"),
    )
    op.create_table(
        "horse_aliases",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("horse_id", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("lang", sa.String(length=4), nullable=False),
        sa.Column("valid_from", sa.Date(), nullable=True),
        sa.Column("valid_to", sa.Date(), nullable=True),
        sa.ForeignKeyConstraint(["horse_id"], ["horses.horse_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("horse_id", "name", "lang", name="uq_alias"),
    )
    op.create_index(op.f("ix_horse_aliases_name"), "horse_aliases", ["name"], unique=False)
    op.create_table(
        "races",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("meeting_id", sa.Integer(), nullable=False),
        sa.Column("race_no", sa.Integer(), nullable=False),
        sa.Column("name", sa.Text(), nullable=True),
        sa.Column("race_class", sa.String(length=32), nullable=True),
        sa.Column("distance_m", sa.Integer(), nullable=True),
        sa.Column("track", sa.String(length=32), nullable=True),
        sa.Column("course", sa.String(length=16), nullable=True),
        sa.Column("going", sa.String(length=64), nullable=True),
        sa.Column("prize", sa.Integer(), nullable=True),
        sa.Column("off_time", sa.DateTime(timezone=True), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.CheckConstraint(
            "status IN ('declared', 'finished', 'abandoned')", name="ck_race_status"
        ),
        sa.ForeignKeyConstraint(["meeting_id"], ["meetings.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("meeting_id", "race_no", name="uq_race_meeting_no"),
    )
    op.create_index("ix_races_status", "races", ["status"], unique=False)
    op.create_table(
        "incident_comments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("race_id", sa.Integer(), nullable=False),
        sa.Column("horse_id", sa.String(length=32), nullable=False),
        sa.Column("jockey_id", sa.Integer(), nullable=True),
        sa.Column("finish_pos", sa.Integer(), nullable=True),
        sa.Column("text_en", sa.Text(), nullable=False),
        sa.Column("source_url", sa.Text(), nullable=True),
        sa.Column("fetched_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["horse_id"], ["horses.horse_id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["jockey_id"],
            ["jockeys.id"],
        ),
        sa.ForeignKeyConstraint(["race_id"], ["races.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("race_id", "horse_id", name="uq_comment_race_horse"),
    )
    op.create_table(
        "runners",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("race_id", sa.Integer(), nullable=False),
        sa.Column("horse_id", sa.String(length=32), nullable=False),
        sa.Column("horse_no", sa.Integer(), nullable=True),
        sa.Column("draw", sa.Integer(), nullable=True),
        sa.Column("jockey_id", sa.Integer(), nullable=True),
        sa.Column("trainer_id", sa.Integer(), nullable=True),
        sa.Column("weight", sa.Integer(), nullable=True),
        sa.Column("actual_weight", sa.Integer(), nullable=True),
        sa.Column("rating", sa.Integer(), nullable=True),
        sa.Column("scratched", sa.Boolean(), nullable=False),
        sa.Column("finish_pos", sa.Integer(), nullable=True),
        sa.Column("finish_time_s", sa.Float(), nullable=True),
        sa.Column("margin", sa.Float(), nullable=True),
        sa.Column("win_odds", sa.Float(), nullable=True),
        sa.Column("sectional_times", sa.JSON(), nullable=True),
        sa.Column("sectional_positions", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(["horse_id"], ["horses.horse_id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["jockey_id"],
            ["jockeys.id"],
        ),
        sa.ForeignKeyConstraint(["race_id"], ["races.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["trainer_id"],
            ["trainers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("race_id", "horse_id", name="uq_runner_race_horse"),
    )
    op.create_index("ix_runners_horse", "runners", ["horse_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_runners_horse", table_name="runners")
    op.drop_table("runners")
    op.drop_table("incident_comments")
    op.drop_index("ix_races_status", table_name="races")
    op.drop_table("races")
    op.drop_index(op.f("ix_horse_aliases_name"), table_name="horse_aliases")
    op.drop_table("horse_aliases")
    op.drop_table("watermarks")
    op.drop_index(op.f("ix_trainers_name_zh"), table_name="trainers")
    op.drop_index(op.f("ix_trainers_name_en"), table_name="trainers")
    op.drop_table("trainers")
    op.drop_index(op.f("ix_meetings_race_date"), table_name="meetings")
    op.drop_table("meetings")
    op.drop_index(op.f("ix_jockeys_name_zh"), table_name="jockeys")
    op.drop_index(op.f("ix_jockeys_name_en"), table_name="jockeys")
    op.drop_table("jockeys")
    op.drop_index("ix_ingest_runs_date", table_name="ingest_runs")
    op.drop_table("ingest_runs")
    op.drop_index(op.f("ix_horses_name_zh"), table_name="horses")
    op.drop_index(op.f("ix_horses_name_en"), table_name="horses")
    op.drop_index(op.f("ix_horses_brand_no"), table_name="horses")
    op.drop_table("horses")
    op.drop_index("ix_chunks_meta", table_name="chunks", postgresql_using="gin")
    op.drop_index(
        "ix_chunks_embedding",
        table_name="chunks",
        postgresql_using="hnsw",
        postgresql_with={"m": 16, "ef_construction": 64},
        postgresql_ops={"embedding": "vector_cosine_ops"},
    )
    op.drop_table("chunks")
    # ### end Alembic commands ###
